on: 
  push:
    branches:
      - master
      
jobs:    
  update_raspi:    
    name: 'Update repo in Raspberry Pi'
    runs-on: ubuntu-latest
    steps:  
      - name: 'Execute tree'
        run: tree
         
      - name: 'Update repo in Raspberry Pi'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: git -C /var/www/html pull
