on: 
  push:
    branches:
      - master
      
jobs:    
  update_raspi:    
    name: 'Update repo in Raspberry Pi'
    runs-on: ubuntu-latest
    steps:  
      - name: 'Execute tree'
        run: tree
         
      - name: 'Update repo in Raspberry Pi'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: chewer.ddns.net
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: whoami
