on: 
  push:
    branches:
      - master
      
jobs:    
  update_raspi:    
    name: 'Update repo on Raspi'
    runs-on: ubuntu-latest
    steps:           
      - name: 'Send "git pull" to Raspi'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: git -C /var/www/djv-raspi pull
